---
- name: Setup image for testing
  hosts: all
  vars:
    conda_home: /opt/conda
  environment:
    PATH: "{{conda_home}}/bin:{{ansible_env.PATH}}"
  roles:
    - evandam.conda
  tasks:
    - name: Install common OS dependencies
      package:
        name:
          - bzip2
          - python-setuptools

    - name: Install dependencies for Debian
      when: ansible_os_family == 'Debian'
      package:
        name: []

    - name: Install dependencies for RedHat
      when: ansible_os_family == 'RedHat'
      package:
        name: []

    - name: Download miniconda installer
      get_url:
        url: "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
        dest: /tmp/miniconda.sh

    - name: Install miniconda
      command: bash /tmp/miniconda.sh -b -p {{conda_home}}
      args:
        creates: "{{conda_home}}"

    - name: Install R with conda
      conda:
        name:
          - r-base
          - r-devtools

    - name: Install python dependencies
      pip:
        name:
          - numpy
          - rpy2
        executable: "{{conda_home}}/bin/pip"
